version: '3'
services:
  db:
    image: mysql:5.7 
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: one_piece
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
